# .github/workflows/docker-frontend.yml
name: Build and Deploy Frontend

on:
  push:
    branches:
      - release-1.0

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and run Docker image
      - name: Build and test Docker image
        run: |
          # Build the image using Dockerfile in src/
          docker build -t frontend-app:1.0 .
          
          # Run the container in background
          docker run -d -p 80:80 --name frontend-test frontend-app:1.0
          
          # Wait a few seconds for server to start
          sleep 5
          
          # Test if the frontend is running (simple HTTP check)
          curl http://localhost || exit 1
          

      # Optional: Push to Docker Hub (uncomment if needed)
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push to Docker Hub
      #   run: |
      #     docker tag frontend-app:latest yourusername/frontend-app:latest
      #     docker push yourusername/frontend-app:latest
